version: '3.9'

services:
  prod-backend:
    image: "examify-backend:0.0.1"
    container_name: examify-be
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "443:443"
    env_file: .env
    # environment:  # comment out when normal development, to avoid rate limits
    #   USE_API_FOR_ADDRESS_AUTOCOMPLETE: y
    volumes:
      - ./backend:/app
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    command: uvicorn main:app --ssl-keyfile ${SSL_KEYFILE} --ssl-certfile ${SSL_CERTFILE} --host 0.0.0.0 --port 443

  prod-frontend:
    image: "examify-frontend:0.0.1"
    container_name: examify-fe
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/client/src
    stdin_open: true
    tty: true

  database:
    image: "examify-database:0.0.1"
    container_name: examify-db
    build: ./backend/database
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: examify-db-debug
    profiles:
      - debug
    restart: always
    ports:
      - "2345:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database
  
  backend:
    image: "examify-backend:0.0.1"
    container_name: examify-be
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    # environment:  # comment out when normal development, to avoid rate limits
    #   USE_API_FOR_ADDRESS_AUTOCOMPLETE: y
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    # dont start unless the database is completely ready
    depends_on:
      database:
        condition: service_healthy

  frontend:
    image: "examify-frontend:0.0.1"
    container_name: examify-fe
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/client/src
    stdin_open: true
    tty: true
    # dont start unless both backend has started and database is completely ready
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_started

  # testing containers
  test-backend:
    image: "examify-test-backend:0.0.1"
    container_name: test-backend
    build:
      context: ./backend
      dockerfile: test.dockerfile
    env_file: .env
    # environment:
    #   TYPECHECK: y
    volumes:
      - ./backend:/app
    depends_on:
      test-database:
        condition: service_healthy

  test-frontend:
    image: "examify-test-frontend:0.0.1"
    container_name: test-frontend
    build:
      context: ./frontend
      dockerfile: test.dockerfile
    volumes:
      - ./frontend/src:/client/src

  test-database:
    image: "examify-test-database:0.0.1"
    container_name: test-database
    build: ./backend/database
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  pgadmin-data: