version: '3.9'

services:
  frontend:
    container_name: examify-frontend
    build: 
      content: ./examify-web
      dockerfile: Frontend/Dockerfile
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./examify-web
          target: /frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./examify-web/package.json
  server:
    container_name: examify-backend
    build: 
      context: ./examify
      dockerfile: Backend/Dockerfile
    ports:
     - 8080:8080