# Generated by Django 3.2.21 on 2023-09-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(default='', max_length=128)),
                ('exam_type', models.CharField(choices=[('TRI', 'TRIAL_EXAM'), ('HSC', 'HSC_EXAM'), ('TOP', 'TOPIC_TEST'), ('HAF', 'HALF_YEARLY_EXAM'), ('T_1', 'TERM_1_EXAM'), ('T_2', 'TERM_2_EXAM'), ('T_3', 'TERM_3_EXAM'), ('T_4', 'TERM_4_EXAM')], max_length=3)),
                ('year', models.PositiveSmallIntegerField()),
                ('file_location', models.FilePathField(unique=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
