# Generated by Django 3.2.24 on 2024-04-14 02:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('TRI', 'TRIAL_EXAM'), ('HSC', 'HSC_EXAM'), ('TOP', 'TOPIC_TEST'), ('HAF', 'HALF_YEARLY_EXAM'), ('T_1', 'TERM_1_EXAM'), ('T_2', 'TERM_2_EXAM'), ('T_3', 'TERM_3_EXAM'), ('T_4', 'TERM_4_EXAM')], max_length=3)),
                ('year', models.PositiveSmallIntegerField()),
                ('file_location', models.FilePathField(unique=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('logo_location', models.FilePathField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('school_year', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('registration_method', models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook')], max_length=128)),
                ('permissions', models.CharField(choices=[('REG', 'REGULAR'), ('PRE', 'PREMIUM'), ('ADM', 'ADMIN')], default='REG', max_length=3)),
                ('school', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.schools')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('refresh_id', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyViewedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.schools'),
        ),
    ]
