# Generated by Django 3.2.24 on 2024-04-14 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook')], max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.schools'),
        ),
    ]
