# Generated by Django 3.2.24 on 2024-04-14 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240414_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook')], max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school_year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
