# Generated by Django 3.2.24 on 2024-04-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_registration_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.CharField(choices=[('REG', 'REGULAR'), ('PRE', 'PREMIUM'), ('ADM', 'ADMIN')], default='REG', max_length=3),
        ),
    ]
