# Generated by Django 3.2.24 on 2024-04-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(default='MX2', max_length=128),
            preserve_default=False,
        ),
    ]
